name: DoxyGen to Sphinx

on:
  pull_request:
    branches:
      - revamp
      - master
  push:
    branches:
      - revamp
      - master
  release:
    branches:
      - revamp
      - master
    types:
      - published
      - edited

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: get latest release version number
      id: latest_ver
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: 2bndy5/RF24
    - name: checkout
      uses: actions/checkout@v2
    - name: overwrite doxygen tags
      run: |
        cd docs
        mkdir doxygen
        touch doxygenAction
        echo "PROJECT_NUMBER = ${{ steps.latest_ver.outputs.release }}" >> doxygenAction
        echo "@INCLUDE = doxygenAction" >> Doxyfile
    - name: run doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
          working-directory: './docs'
          doxyfile-path: './Doxyfile'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install Sphinx extensions
      run: pip install -r docs/requirements.txt
    - name: run Sphinx
      run: |
        cd docs
        sphinx-build -E -W . _build
    - name: upload to github pages
      # if: ${{ github.event_name == 'release'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build